=== Alberto-iesfm/ies-federica-montseny/1DAM/Lenguajes_de_marcas/DTD/dtd.dtd
<!ELEMENT company (nombreCompañia,empleados)>
<!ELEMENT nombreCompañia (#PCDATA)>
<!ELEMENT empleados (empleado*)>
<!ELEMENT empleado (nombre,apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

=== Alberto-iesfm/ies-federica-montseny/1DAM/Lenguajes_de_marcas/DTD/example.xml
<?xml version="1.0"?>
<!DOCTYPE company SYSTEM "dtd.dtd">

<company>
    <nombreCompañia>compañia 1</nombreCompañia>
    <empleados>
        <empleado>
            <nombre>Juan</nombre>
            <apellidos>Perez Diaz</apellidos>
        </empleado>
        <empleado>
            <nombre>Pedro</nombre>
            <apellidos>Hierro Fernandez</apellidos>
        </empleado>
    </empleados>
</company>
